const express = require('express')
const router = express.Router()
const authMiddleWare=require("../../middlewares/auth")
const uploadAvatar=require("../../controllers/avatars/uploadAvatar")
const getCurrent=require("../../controllers/users/getCurrent")
const ctrlWrapper=require("../../middlewares/ctrlWrapper")
const auth  = require('../../middlewares/auth')
const multer=require("../../middlewares/multer")
const verifyMail=require("../../controllers/users/verifyMail")
const secondVerify=require("../../controllers/users/secondVerify")
const confirmEmail=require("../../controllers/users/confirmEmail")
const confirmedToken=require("../../controllers/users/confirmedToken")
const resetPassword=require("../../controllers/users/resetPassword")

router.get("/current",authMiddleWare,ctrlWrapper(getCurrent))
router.patch("/avatars",auth, multer.single("avatar"),ctrlWrapper(uploadAvatar))
router.get("/verify/:verificationToken",ctrlWrapper(verifyMail))
router.post("/verify",ctrlWrapper(secondVerify))
router.post("/confirmEmail",ctrlWrapper(confirmEmail))
router.get("/confirmEmail/:confirmationToken",ctrlWrapper(confirmedToken))
router.post("/resetPassword",ctrlWrapper(resetPassword))
module.exports=router